package org.kie.kogito.examples.iot.rules;
unit AlertedSystem;

import org.kie.kogito.examples.iot.data.DoorSensorData;

rule alertedNoIntruder when
    /updates[ !isAlerted() ]
then
    System.out.println("situation back to normal (alerted)");
    result.append("SITUATION_NORMAL");
end

rule alertedIntruderAtTheDoor when
    msg: /updates[ isAlerted() ]
then
    System.out.println("situation still abnormal: " + msg);
    result.append("INTRUDER_DETECTED");
end
